<?php

return [
    'default_weight' => 1.0,
    'game_weights' => [
        'memory_game' => 1.2,
        'simon_says' => 1.1,
        'snake_retro' => 1.2,
        'whack_a_mole' => 1.2,
        'tower_blocks' => 1.15,
        'canon_defender' => 1.15,
        'math_sprint' => 1.1,
        'maze_runner' => 1.0,
        'tile_puzzle' => 0.95,
        'image_puzzle' => 0.95,
        'sudoku' => 0.9,
        'sudoku_pro' => 0.9,
        'tic_tac_toe' => 0.9,
        'tetris' => 1.0,
        'tetris_block' => 1.0,
        'word_scramble' => 0.95,
        'spelling_bee' => 0.95,
        'hangman_quest' => 0.95,
        'synonym_challenge' => 0.95,
        'cut_the_rope' => 1.0,
    ],
    'baseline_latency_ms' => [
        'memory_game' => [
            '4-6' => 2500,
            '7-9' => 1600,
            '10-12' => 1000,
        ],
        'snake_retro' => [
            '4-6' => 1200,
            '7-9' => 800,
            '10-12' => 500,
        ],
        'whack_a_mole' => [
            '4-6' => 1500,
            '7-9' => 900,
            '10-12' => 650,
        ],
        'tower_blocks' => [
            '4-6' => 1500,
            '7-9' => 900,
            '10-12' => 650,
        ],
        'canon_defender' => [
            '4-6' => 1500,
            '7-9' => 900,
            '10-12' => 650,
        ],
        'default' => [
            '4-6' => 2000,
            '7-9' => 1300,
            '10-12' => 900,
        ],
    ],
    'baseline_error_rate' => [
        '4-6' => 0.20,
        '7-9' => 0.12,
        '10-12' => 0.06,
    ],
    'decay_interval_ms' => 30000,
    'decay_multiplier' => 0.8,
    'boredom_latency_ratio' => 2.0,
    'boredom_consecutive' => 3,
    'boredom_long_pause_ms' => 10000,
    'focus_latency_variance' => 0.15,
    'focus_consecutive_success' => 3,
    'quick_recovery_multiplier' => 1.2,
    'frustration_spam_window_ms' => 500,
    'frustration_spam_count' => 3,
    'frustration_error_spiral_window_ms' => 3000,
    'joy_success_streak' => 5,
    'analysis_weights' => [
        'previous_1' => 0.10,
        'previous_2' => 0.03,
    ],
    'analysis_weights_decay_days' => 7.0,
    'data_quality_weights' => [
        'raw_signals' => 1.0,
        'summary_only' => 0.6,
        'no_data' => 0.0,
    ],
    'min_sessions' => 2,
];
